name: Verificación

on:
  push:
    branches: [main, feat/qupuy-portal]
  pull_request:
    branches: [main]

jobs:
  nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Instalar dependencias
        run: yarn install --immutable

      - name: Lint
        run: yarn next:lint --max-warnings=0

      - name: Tipos
        run: yarn next:check-types

      - name: Tests de lógica
        run: yarn workspace @se-2/nextjs test
